### ISSUE TITLE
TLS Cert should be a kubernetes secret

### ISSUE THREAD

**Issue by beemarie** [knative-sandbox/eventing-redis#162]
**Describe the bug**
TLS cert should be in a kube secret

 **Expected behavior**
TLS cert is currently in a config map, should be a kubernetes secret.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by juliafriedman8** [comment]
assign @juliafriedman8

**Comment by aavarghese** [comment]
@juliafriedman8 will complete the work to change the K8 Secret into a kubernetes.io/tls type (adding to @beemarie's PR)

**Comment by aavarghese** [comment]
@juliafriedman8 please also make the updates for TLS cert secret in https://github.com/knative-sandbox/eventing-redis/blob/main/sink/config/config-tls.yaml too
