### ISSUE TITLE
It appears that stream source component is dropping some requests

### ISSUE THREAD

**Issue by beemarie** [knative-sandbox/eventing-redis#34]
**Describe the bug**
When doing some load testing of the async-component, I noticed that some requests are lost. It looks like the requests are not being sent to my sink.

 **Expected behavior**
I would expect all items to be sent to my sink. Maybe we should retry failed requests?

 **To Reproduce**
I'm using the loadtest NPM module to make 10 requests per second for 20 seconds to my application. You can see setup instructions for the async component in our sandbox project:  https://github.com/knative-sandbox/async-component

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aavarghese** [comment]
@beemarie as we discussed on Slack, I haven't been able to reproduce this request drops (500 return codes).

My setup involved using the hello-world application and running with both "75" and "5000" numConsumers (for redis).
Load testing was done via `loadtest -c 10 --rps 20 -t 20 http://helloworld-sleep.default.169.61.147.82.xip.io?duration=10 -H Prefer:respond-async` about 400 requests...

Let me know your thoughts. 
Either way, I think it will benefit to add a re-try mechanism to RedisStreamSource's adapter. Will push that out soon.
